name: Run Tests (Go)

on:
  pull_request:
    paths:
      - '**.go'
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # release, e.g. v0.0.0
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+' # pre-release, e.g. v0.0.0-rc0

jobs:
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install mage
        uses: magefile/mage-action@v3
        with:
            install-only: true
      - name: Install golangci-lint
        env:
          VERSION: v1.56.2
        run: bash curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${VERSION}
      # Steps Executed on PRs
      - name: mage ci
        run: mage ci
        env:
          VERBOSE: 1
        if: github.event_name == 'pull_request'
      # Steps Executed On Release
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        if: github.event_name == 'push'
      - name: mage release
        run: mage release
        env:
          VERBOSE: 1
        if: github.event_name == 'push'
